# Generated by Django 3.1.6 on 2021-02-17 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Logs', '0003_auto_20210217_0554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activityperiod',
            old_name='user_id',
            new_name='user',
        ),
    ]
